apiVersion: v1
kind: Secret
metadata:
  name: tap-gui
  namespace: tap-gui
data:
  tls.crt: “base64 of /etc/letsencrypt/tap-gui.example.com/fullchain.pem”
  tls.key: “base64 of /etc/letsencrptlive/tap-gui.example.com/privkey.pem”
type: kubernetes.io/tls